### ISSUE TITLE
首页tab文字居中问题

### ISSUE THREAD

**Issue by zxc0328** [Muxi-Studio/guisheng_fe#1]
首页的tab在选中状态下上面会有绿色的边框，但是那个边框的出现会导致文字往下移几个像素，和其他的tab item中的文字没有对齐。

一般这个情况我们会给普通的tab设置一个和背景颜色一样的border，选中后不是添加border而是修改border的颜色。这样盒子的高度就一直都不变，垂直居中就不会出问题

**Comment by zxc0328** [comment]
建议以后关issue的时候附上commit的链接

**Comment by Elegenthus** [comment]
https://github.com/Muxi-Studio/guisheng_fe/commit/8aacf631f37bdd2290e23e50e71a0790bd089e30

好👌
