### ISSUE TITLE
返回问题

### ISSUE THREAD

**Issue by Anrous** [Muxi-Studio/guisheng_fe#3]
<bug>桂声部分地方无法返回上一级，如水墨中的文章，只能跳转到首页，或直接跳出网站

**Comment by zxc0328** [comment]
使用 window.history.back() 返回，修复后回复commit链接再close

**Comment by Elegenthus** [comment]
[已解决](http://120.24.4.254:8777/)

[commit](https://github.com/hdgs/guisheng_fe/commit/e5d836bcdf73739873990b048336831c99d1a3f1)
